// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEN0eGV0yy0q-ydNcy_S2E1-xyf_K-SY',
    appId: '1:525220056646:web:74bf7a4414abbaff968447',
    messagingSenderId: '525220056646',
    projectId: 'ampify-with-bloc',
    authDomain: 'ampify-with-bloc.firebaseapp.com',
    storageBucket: 'ampify-with-bloc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUFhb_UiIuz7B289tNolsLWdpyiPMOzM',
    appId: '1:525220056646:android:0f1ca45632ce6e07968447',
    messagingSenderId: '525220056646',
    projectId: 'ampify-with-bloc',
    storageBucket: 'ampify-with-bloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFZoXa-igdhbfu_o7o0yfN2aX_5y4mzM8',
    appId: '1:525220056646:ios:e09d62c81c26b02a968447',
    messagingSenderId: '525220056646',
    projectId: 'ampify-with-bloc',
    storageBucket: 'ampify-with-bloc.firebasestorage.app',
    androidClientId: '525220056646-3idq2hasso76u7u81rrr6p41d1dv0o4i.apps.googleusercontent.com',
    iosClientId: '525220056646-fqhoqm4elf9u7lpqeqvqev2fclto3m5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ampifyBloc',
  );
}
